In [6]:
import pandas as pd
import geopandas as gpd
from shapely.geometry import Polygon, Point
import numpy as np

In [3]:
data = pd.read_csv('./data/location.csv')

data.head()

,sampno,locno,perno,loctype,state,country,state_fips,county_fips,tract_fips,out_region,home,latitude,longitude
0,20000083,10000,-1,1,IL,USA,17,31,802403,0,1,42.141870,-87.953126
1,20000083,10002,1,2,IL,USA,17,31,801601,0,0,42.145289,-87.863023
2,20000083,10401,-1,4,IL,USA,17,31,801606,0,0,42.116325,-87.868708
3,20000083,10402,-1,4,IL,USA,17,31,803007,0,0,42.131743,-87.970674
4,20000083,10403,-1,4,IL,USA,17,31,802504,0,0,42.134326,-87.937060

In [4]:
data = pd.read_csv('./data/location.csv')


data = data.loc[(data.loctype == 1) | (data.loctype == 2) | (data.loctype == 3)]

v = data.sampno.value_counts()

data = data[data.sampno.apply(lambda x: v[x] > 1)]

data

,sampno,locno,perno,loctype,state,country,state_fips,county_fips,tract_fips,out_region,home,latitude,longitude
0,20000083,10000,-1,1,IL,USA,17,31,802403,0,1,42.141870,-87.953126
1,20000083,10002,1,2,IL,USA,17,31,801601,0,0,42.145289,-87.863023
11,20000136,10000,-1,1,IL,USA,17,31,81402,0,1,41.891022,-87.612931
12,20000136,10002,1,2,IL,USA,17,31,830900,0,0,41.928424,-87.684906
17,20000136,20002,2,2,IL,USA,17,31,81401,0,0,41.895035,-87.619717
...,...,...,...,...,...,...,...,...,...,...,...,...,...
110062,70100988,20003,2,3,IL,USA,17,31,281900,0,0,41.878635,-87.642924
110071,70100992,10000,-1,1,IL,USA,17,97,864519,0,1,42.165420,-87.959139
110072,70100992,10002,1,2,IL,USA,17,97,864205,0,0,42.292549,-88.141232
110074,70100993,10000,-1,1,IL,USA,17,31,260700,0,1,41.877056,-87.727996
110075,70100993,20002,2,2,IL,USA,17,43,844401,0,0,41.828246,-88.016876

In [18]:
import tqdm

In [31]:
tracts = gpd.read_file('osmnx/data/tracts.geojson')

tract_sampno = [None for i in range(len(data.index))]

for i in tqdm.tqdm(range(len(data.index))):
    s = data.iloc[i]
    for row in tracts.iloc:
        if row.geometry.contains(Point(s.longitude, s.latitude)):
            tract_sampno[i] = row.namelsad10
            break
            

data

100%|██████████| 32922/32922 [19:50<00:00, 27.66it/s]

,sampno,locno,perno,loctype,state,country,state_fips,county_fips,tract_fips,out_region,home,latitude,longitude,tract
0,20000083,10000,-1,1,IL,USA,17,31,802403,0,1,42.141870,-87.953126,0.0
1,20000083,10002,1,2,IL,USA,17,31,801601,0,0,42.145289,-87.863023,0.0
11,20000136,10000,-1,1,IL,USA,17,31,81402,0,1,41.891022,-87.612931,0.0
12,20000136,10002,1,2,IL,USA,17,31,830900,0,0,41.928424,-87.684906,0.0
17,20000136,20002,2,2,IL,USA,17,31,81401,0,0,41.895035,-87.619717,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110062,70100988,20003,2,3,IL,USA,17,31,281900,0,0,41.878635,-87.642924,0.0
110071,70100992,10000,-1,1,IL,USA,17,97,864519,0,1,42.165420,-87.959139,0.0
110072,70100992,10002,1,2,IL,USA,17,97,864205,0,0,42.292549,-88.141232,0.0
110074,70100993,10000,-1,1,IL,USA,17,31,260700,0,1,41.877056,-87.727996,0.0
110075,70100993,20002,2,2,IL,USA,17,43,844401,0,0,41.828246,-88.016876,0.0

In [ ]:
data['tract'] = tract_sampno

data.to_csv('./data/tract_location.csv')

In [45]:
filtered = pd.DataFrame(columns=data.columns)

for s in data.sampno.unique():
    snip = data.loc[data.sampno == s]
    if None in list(snip.tract): continue

    filtered = pd.concat([filtered, snip])

/tmp/ipykernel_126372/425088475.py:7: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  filtered = pd.concat([filtered, snip])

,sampno,locno,perno,loctype,state,country,state_fips,county_fips,tract_fips,out_region,home,latitude,longitude,tract
11,20000136,10000,-1,1,IL,USA,17,31,81402,0,1,41.891022,-87.612931,Census Tract 814.02
12,20000136,10002,1,2,IL,USA,17,31,830900,0,0,41.928424,-87.684906,Census Tract 8309
17,20000136,20002,2,2,IL,USA,17,31,81401,0,0,41.895035,-87.619717,Census Tract 814.01
35,20000300,10000,-1,1,IL,USA,17,31,81300,0,1,41.898335,-87.620753,Census Tract 813
36,20000300,10002,1,2,IL,USA,17,31,281900,0,0,41.878635,-87.642924,Census Tract 2819
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110044,70100917,10000,-1,1,IL,USA,17,31,690300,0,1,41.768733,-87.629116,Census Tract 6903
110045,70100917,30003,3,3,IL,USA,17,31,690300,0,0,41.768733,-87.629116,Census Tract 6903
110060,70100988,10000,-1,1,IL,USA,17,31,834300,0,1,41.745835,-87.591788,Census Tract 8343
110061,70100988,10003,1,3,IL,USA,17,31,281900,0,0,41.878635,-87.642924,Census Tract 2819
110062,70100988,20003,2,3,IL,USA,17,31,281900,0,0,41.878635,-87.642924,Census Tract 2819

In [66]:
sampnos = filtered.sampno.unique()

origin_dest_pairs = {}

for s in sampnos:
    origin = list(filtered.loc[(filtered.sampno == s) & (filtered.home == 1)].tract)[0]
    destinations = list(filtered.loc[(filtered.sampno == s) & (filtered.home == 0)].tract)
    print(destinations)
    origin_dest_pairs.setdefault(origin, [])

    for d in destinations:
        origin_dest_pairs[origin] += [d]

['Census Tract 8309', 'Census Tract 814.01']
['Census Tract 2819']
['Census Tract 8381', 'Census Tract 207.01']
['Census Tract 814.01', 'Census Tract 8431']
['Census Tract 8391']
['Census Tract 8391']
['Census Tract 7608.01']
['Census Tract 3201']
['Census Tract 815']
['Census Tract 8391']
['Census Tract 714']
['Census Tract 8391']
['Census Tract 8391']
['Census Tract 7201', 'Census Tract 3818']
['Census Tract 2819']
['Census Tract 2801']
['Census Tract 2420']
['Census Tract 8391']
['Census Tract 8391']
['Census Tract 3201']
['Census Tract 8391', 'Census Tract 817']
['Census Tract 814.01', 'Census Tract 3204']
['Census Tract 8391']
['Census Tract 1610']
['Census Tract 3201', 'Census Tract 8391']
['Census Tract 4204', 'Census Tract 208.02']
['Census Tract 8362', 'Census Tract 8362']
['Census Tract 818', 'Census Tract 814.01']
['Census Tract 814.03', 'Census Tract 501', 'Census Tract 602']
['Census Tract 5003']
['Census Tract 3204']
['Census Tract 8419']
['Census Tract 8411']
['Census Tract 813']
['Census Tract 8391', 'Census Tract 8391']
['Census Tract 8391', 'Census Tract 812.01']
['Census Tract 8433']
['Census Tract 8422']
['Census Tract 2433']
['Census Tract 8391', 'Census Tract 8330']
['Census Tract 8419']
['Census Tract 3201', 'Census Tract 8423']
['Census Tract 9801']
['Census Tract 2412']
['Census Tract 8388']
['Census Tract 2420', 'Census Tract 812.02']
['Census Tract 404.02']
['Census Tract 2415']
['Census Tract 818']
['Census Tract 8362', 'Census Tract 8362', 'Census Tract 8362', 'Census Tract 8362']
['Census Tract 3301']
['Census Tract 3204', 'Census Tract 8391']
['Census Tract 7608.03', 'Census Tract 9800', 'Census Tract 610']
['Census Tract 8391']
['Census Tract 8391']
['Census Tract 710', 'Census Tract 8330', 'Census Tract 710', 'Census Tract 3204', 'Census Tract 8331']
['Census Tract 8419']
['Census Tract 8362']
['Census Tract 1202']
['Census Tract 4112', 'Census Tract 8391']
['Census Tract 814.01', 'Census Tract 602']
['Census Tract 1101']
['Census Tract 8435']
['Census Tract 814.03', 'Census Tract 3201']
['Census Tract 8391', 'Census Tract 2819']
['Census Tract 812.01']
['Census Tract 1003']
['Census Tract 8391', 'Census Tract 8382']
['Census Tract 3201']
['Census Tract 8391']
['Census Tract 8391', 'Census Tract 403', 'Census Tract 403']
['Census Tract 3204']
['Census Tract 8391', 'Census Tract 3201']
['Census Tract 3201']
['Census Tract 8391', 'Census Tract 3201', 'Census Tract 8390']
['Census Tract 8391']
['Census Tract 318', 'Census Tract 318']
['Census Tract 2819', 'Census Tract 505']
['Census Tract 3201', 'Census Tract 8362', 'Census Tract 633.01']
['Census Tract 2819', 'Census Tract 8419']
['Census Tract 104', 'Census Tract 408', 'Census Tract 408']
['Census Tract 2819']
['Census Tract 3201', 'Census Tract 3501', 'Census Tract 5002', 'Census Tract 8329']
['Census Tract 8391', 'Census Tract 8362']
['Census Tract 8391']
['Census Tract 8391', 'Census Tract 8362', 'Census Tract 8362']
['Census Tract 8391', 'Census Tract 2204', 'Census Tract 2413']
['Census Tract 817', 'Census Tract 712']
['Census Tract 2819', 'Census Tract 3301']
['Census Tract 2819', 'Census Tract 818']
['Census Tract 3204', 'Census Tract 3201', 'Census Tract 803', 'Census Tract 803']
['Census Tract 602', 'Census Tract 305']
['Census Tract 8319', 'Census Tract 8422', 'Census Tract 8330']
['Census Tract 8391', 'Census Tract 8312']
['Census Tract 8391', 'Census Tract 817']
['Census Tract 8419', 'Census Tract 8419', 'Census Tract 604']
['Census Tract 816', 'Census Tract 3201', 'Census Tract 2819']
['Census Tract 707', 'Census Tract 1610']
['Census Tract 8391', 'Census Tract 2801']
['Census Tract 2308']
['Census Tract 8391', 'Census Tract 8330']
['Census Tract 8437', 'Census Tract 9800', 'Census Tract 8383']
['Census Tract 3201', 'Census Tract 403', 'Census Tract 718', 'Census Tract 718']
['Census Tract 3201', 'Census Tract 3201']
['Census Tract 8362']
['Census Tract 3201', 'Census Tract 8391']
['Census Tract 814.02', 'Census Tract 3204']
['Census Tract 3201', 'Census Tract 8391']
['Census Tract 8391']
['Census Tract 8308']
['Census Tract 8391', 'Census Tract 501']
['Census Tract 8391']
['Census Tract 818']
['Census Tract 8419', 'Census Tract 8362']
['Census Tract 2435', 'Census Tract 8391', 'Census Tract 2424', 'Census Tract 8309']
['Census Tract 3201']
['Census Tract 701.02', 'Census Tract 3201']
['Census Tract 2801', 'Census Tract 8391']
['Census Tract 8391', 'Census Tract 501', 'Census Tract 1408']
['Census Tract 8330', 'Census Tract 8419', 'Census Tract 2801']
['Census Tract 8391']
['Census Tract 8419', 'Census Tract 8397']
['Census Tract 714']
['Census Tract 2819']
['Census Tract 8419', 'Census Tract 8382', 'Census Tract 8420']
['Census Tract 8391', 'Census Tract 1407.02', 'Census Tract 3204']
['Census Tract 8391']
['Census Tract 3204']
['Census Tract 8391']
['Census Tract 8391']
['Census Tract 2819', 'Census Tract 8391']
['Census Tract 8391']
['Census Tract 8391']
['Census Tract 8391']
['Census Tract 8391']
['Census Tract 3201', 'Census Tract 1610']
['Census Tract 8391']
['Census Tract 8382']
['Census Tract 814.03', 'Census Tract 3201']
['Census Tract 2801']
['Census Tract 8391', 'Census Tract 9800', 'Census Tract 1004', 'Census Tract 1004']
['Census Tract 814.03', 'Census Tract 8420']
['Census Tract 7504']
['Census Tract 8382', 'Census Tract 8382']
[]
['Census Tract 8419', 'Census Tract 501', 'Census Tract 501']
['Census Tract 8391', 'Census Tract 8391', 'Census Tract 8326', 'Census Tract 8326']
['Census Tract 8391']
['Census Tract 2801']
['Census Tract 6115', 'Census Tract 104']
['Census Tract 3204']
['Census Tract 8391']
['Census Tract 8391', 'Census Tract 4203']
['Census Tract 8391', 'Census Tract 704', 'Census Tract 8391']
['Census Tract 3201', 'Census Tract 8391', 'Census Tract 8422']
['Census Tract 3201', 'Census Tract 814.01']
['Census Tract 8391', 'Census Tract 814.01']
['Census Tract 8329', 'Census Tract 1002']
['Census Tract 8306', 'Census Tract 308', 'Census Tract 308']
['Census Tract 8391', 'Census Tract 8391', 'Census Tract 8383']
['Census Tract 815']
['Census Tract 814.01', 'Census Tract 3201']
['Census Tract 8391']
['Census Tract 8382']
['Census Tract 3905', 'Census Tract 3905', 'Census Tract 4109']
['Census Tract 8391']
['Census Tract 8391', 'Census Tract 2819']
['Census Tract 8391']
['Census Tract 8391']
['Census Tract 8391', 'Census Tract 104']
['Census Tract 817']
['Census Tract 2801']
['Census Tract 8391']
['Census Tract 626']
['Census Tract 803']
['Census Tract 8381']
['Census Tract 8391', 'Census Tract 8391']
['Census Tract 8391', 'Census Tract 8390', 'Census Tract 8331', 'Census Tract 8383']
['Census Tract 2801', 'Census Tract 1003']
['Census Tract 817', 'Census Tract 301.03', 'Census Tract 318']
['Census Tract 8391', 'Census Tract 8321', 'Census Tract 8390', 'Census Tract 712']
['Census Tract 8391']
['Census Tract 2819']
['Census Tract 8370', 'Census Tract 3201']
['Census Tract 8391']
['Census Tract 8318']
['Census Tract 3201', 'Census Tract 8391', 'Census Tract 8437']
['Census Tract 3206']
['Census Tract 3204']
['Census Tract 3201', 'Census Tract 814.03', 'Census Tract 8390', 'Census Tract 814.03', 'Census Tract 8390']
['Census Tract 8391', 'Census Tract 8391', 'Census Tract 8330']
['Census Tract 611']
['Census Tract 3201']
['Census Tract 8391']
['Census Tract 8391']
['Census Tract 8391']
['Census Tract 814.01']
['Census Tract 811']
['Census Tract 3302', 'Census Tract 3302']
['Census Tract 8391', 'Census Tract 814.01', 'Census Tract 8331', 'Census Tract 8383']
['Census Tract 8322', 'Census Tract 8319', 'Census Tract 8319']
['Census Tract 8422']
['Census Tract 6502']
['Census Tract 8391', 'Census Tract 2801']
['Census Tract 8382']
['Census Tract 818']
['Census Tract 1912', 'Census Tract 3801', 'Census Tract 718']
['Census Tract 2819']
['Census Tract 8391']
['Census Tract 3201']
['Census Tract 3204', 'Census Tract 2209.02']
['Census Tract 8391', 'Census Tract 814.01']
['Census Tract 813', 'Census Tract 203.01']
['Census Tract 3201', 'Census Tract 3201']
['Census Tract 8382']
['Census Tract 8362', 'Census Tract 814.03']
['Census Tract 7112', 'Census Tract 2819']
['Census Tract 209.02', 'Census Tract 8367', 'Census Tract 209.02']
['Census Tract 4112', 'Census Tract 8362', 'Census Tract 8362', 'Census Tract 8362', 'Census Tract 8362']
['Census Tract 8362', 'Census Tract 501']
['Census Tract 3204']
['Census Tract 8391']
['Census Tract 8391']
['Census Tract 816', 'Census Tract 8391']
['Census Tract 8422', 'Census Tract 817']
['Census Tract 812.01']
['Census Tract 815']
['Census Tract 8362', 'Census Tract 8362']
['Census Tract 4110']
['Census Tract 814.01']
['Census Tract 818']
['Census Tract 4110', 'Census Tract 3201']
['Census Tract 8391']
['Census Tract 6715']
['Census Tract 2801']
['Census Tract 9800', 'Census Tract 2819']
['Census Tract 8382']
['Census Tract 3201']
['Census Tract 817', 'Census Tract 2801']
['Census Tract 8391']
['Census Tract 8391']
['Census Tract 8391']
['Census Tract 403']
['Census Tract 815']
['Census Tract 8391']
['Census Tract 401', 'Census Tract 3201']
['Census Tract 8391', 'Census Tract 8331']
['Census Tract 308']
['Census Tract 3201', 'Census Tract 8437']
['Census Tract 817', 'Census Tract 8362']
['Census Tract 3301']
['Census Tract 8391', 'Census Tract 8391']
['Census Tract 2801']
['Census Tract 8391', 'Census Tract 8373']
['Census Tract 8391', 'Census Tract 3204', 'Census Tract 3204', 'Census Tract 3204']
['Census Tract 2431', 'Census Tract 3201', 'Census Tract 2203']
['Census Tract 8382', 'Census Tract 8362']
['Census Tract 8391', 'Census Tract 814.03']
['Census Tract 3204', 'Census Tract 814.01']
['Census Tract 3201']
['Census Tract 3201', 'Census Tract 4110']
['Census Tract 8391', 'Census Tract 1105.01', 'Census Tract 1506']
['Census Tract 2801']
['Census Tract 8391']
['Census Tract 8391', 'Census Tract 811']
['Census Tract 8391']
['Census Tract 8422', 'Census Tract 3204']
['Census Tract 8312']
['Census Tract 2819', 'Census Tract 814.01']
['Census Tract 8329', 'Census Tract 2831', 'Census Tract 8391']
['Census Tract 8391', 'Census Tract 710', 'Census Tract 710']
['Census Tract 8382', 'Census Tract 4110', 'Census Tract 312']
['Census Tract 206.01', 'Census Tract 8318']
['Census Tract 8382']
['Census Tract 4106']
['Census Tract 814.02']
['Census Tract 8419']
['Census Tract 8428']
['Census Tract 818', 'Census Tract 818']
['Census Tract 8331']
['Census Tract 814.01', 'Census Tract 8419']
['Census Tract 8391', 'Census Tract 3201', 'Census Tract 7502']
['Census Tract 8330', 'Census Tract 8330']
['Census Tract 3204']
['Census Tract 314', 'Census Tract 8319', 'Census Tract 814.01']
['Census Tract 818']
['Census Tract 3201']
['Census Tract 8306']
['Census Tract 8391']
['Census Tract 818']
['Census Tract 8391']
['Census Tract 8330']
['Census Tract 8391']
['Census Tract 817']
['Census Tract 814.01', 'Census Tract 8423']
['Census Tract 8391']
['Census Tract 8362', 'Census Tract 8362']
['Census Tract 8391']
['Census Tract 1202']
['Census Tract 2801', 'Census Tract 8432']
['Census Tract 6809']
['Census Tract 3204']
['Census Tract 3201', 'Census Tract 1003']
['Census Tract 2801']
['Census Tract 8419', 'Census Tract 1301']
['Census Tract 506']
['Census Tract 8391']
['Census Tract 8391', 'Census Tract 1005', 'Census Tract 602']
['Census Tract 4203', 'Census Tract 812.01', 'Census Tract 714']
['Census Tract 8391']
['Census Tract 8391']
['Census Tract 8391']
['Census Tract 9800', 'Census Tract 815', 'Census Tract 710']
['Census Tract 306.01', 'Census Tract 104', 'Census Tract 104']
['Census Tract 3201']
['Census Tract 818']
['Census Tract 3206']
['Census Tract 814.03', 'Census Tract 3204']
['Census Tract 813']
['Census Tract 611']
['Census Tract 3204']
['Census Tract 8391']
['Census Tract 812.01', 'Census Tract 802.02']
['Census Tract 104', 'Census Tract 406', 'Census Tract 710']
['Census Tract 620']
['Census Tract 8391']
['Census Tract 8391', 'Census Tract 2422']
['Census Tract 812.01', 'Census Tract 3204']
['Census Tract 404.02', 'Census Tract 703', 'Census Tract 1003', 'Census Tract 1003']
['Census Tract 8330']
['Census Tract 8391']
['Census Tract 710', 'Census Tract 3204', 'Census Tract 3204', 'Census Tract 3204']
['Census Tract 8431']
['Census Tract 3204']
['Census Tract 8391', 'Census Tract 8391']
['Census Tract 8431']
['Census Tract 8391']
['Census Tract 301.04', 'Census Tract 104', 'Census Tract 3106']
['Census Tract 8391', 'Census Tract 8391']
['Census Tract 8391', 'Census Tract 8391', 'Census Tract 506']
['Census Tract 814.01']
['Census Tract 8391', 'Census Tract 1005']
['Census Tract 8382']
['Census Tract 8423', 'Census Tract 8308', 'Census Tract 8308', 'Census Tract 8308']
['Census Tract 705']
['Census Tract 8410']
['Census Tract 8391']
['Census Tract 5704']
['Census Tract 2819']
['Census Tract 814.01', 'Census Tract 628']
['Census Tract 3301']
['Census Tract 8391', 'Census Tract 7203', 'Census Tract 8422']
['Census Tract 8391']
['Census Tract 8391', 'Census Tract 8391', 'Census Tract 817']
['Census Tract 3201', 'Census Tract 8391']
['Census Tract 3201', 'Census Tract 8437']
['Census Tract 8391', 'Census Tract 8318']
['Census Tract 2819', 'Census Tract 203.02']
['Census Tract 8391', 'Census Tract 810']
['Census Tract 8382']
['Census Tract 2435']
['Census Tract 9800', 'Census Tract 3107']
['Census Tract 104', 'Census Tract 812.01', 'Census Tract 1603']
['Census Tract 8333', 'Census Tract 8333']
['Census Tract 8422']
['Census Tract 3204']
['Census Tract 814.01', 'Census Tract 8391']
['Census Tract 2819']
['Census Tract 8330']
['Census Tract 2428', 'Census Tract 2428']
['Census Tract 3204', 'Census Tract 2315']
['Census Tract 8391']
['Census Tract 3204', 'Census Tract 8319', 'Census Tract 8319']
['Census Tract 3204', 'Census Tract 4110']
['Census Tract 8391']
['Census Tract 8382']
['Census Tract 8391']
['Census Tract 813', 'Census Tract 8104']
['Census Tract 6706']
['Census Tract 8391', 'Census Tract 3204']
['Census Tract 7107', 'Census Tract 321', 'Census Tract 7107']
['Census Tract 8391']
['Census Tract 9800']
['Census Tract 814.01']
['Census Tract 3109', 'Census Tract 712', 'Census Tract 1606.01', 'Census Tract 1606.01']
['Census Tract 3201', 'Census Tract 8422']
['Census Tract 8331', 'Census Tract 3201', 'Census Tract 404.02', 'Census Tract 8391']
['Census Tract 8331', 'Census Tract 2819']
['Census Tract 8391']
['Census Tract 712', 'Census Tract 710']
['Census Tract 813', 'Census Tract 8391']
['Census Tract 8391', 'Census Tract 8391']
['Census Tract 622']
['Census Tract 3201', 'Census Tract 3204']
['Census Tract 8391']
['Census Tract 815']
['Census Tract 3201']
['Census Tract 2819']
['Census Tract 3201']
['Census Tract 702']
['Census Tract 2421']
['Census Tract 814.01', 'Census Tract 814.01']
['Census Tract 3204', 'Census Tract 3204']
['Census Tract 8391', 'Census Tract 3201']
['Census Tract 8330']
['Census Tract 2819', 'Census Tract 818']
['Census Tract 1610', 'Census Tract 8391']
['Census Tract 8391', 'Census Tract 3201', 'Census Tract 710', 'Census Tract 8391']
['Census Tract 627']
['Census Tract 8391', 'Census Tract 9800']
['Census Tract 3204']
['Census Tract 2205', 'Census Tract 2205']
['Census Tract 4110']
['Census Tract 8435']
['Census Tract 2801', 'Census Tract 8391', 'Census Tract 8308']
['Census Tract 403', 'Census Tract 8410']
['Census Tract 8391']
['Census Tract 2819']
['Census Tract 3204', 'Census Tract 5906']
['Census Tract 8382', 'Census Tract 8391']
['Census Tract 8331', 'Census Tract 8383', 'Census Tract 3907']
['Census Tract 3201']
['Census Tract 8391', 'Census Tract 3907']
['Census Tract 815']
['Census Tract 8381']
['Census Tract 817']
['Census Tract 8391']
['Census Tract 814.01', 'Census Tract 8333', 'Census Tract 301.03', 'Census Tract 301.03']
['Census Tract 8391']
['Census Tract 818', 'Census Tract 8391']
['Census Tract 7608.01', 'Census Tract 2819']
['Census Tract 8391', 'Census Tract 8382']
['Census Tract 3204', 'Census Tract 8308']
['Census Tract 8391', 'Census Tract 5907']
['Census Tract 8391']
['Census Tract 817']
['Census Tract 2801']
['Census Tract 8391']
['Census Tract 301.04', 'Census Tract 301.04']
['Census Tract 817', 'Census Tract 8391', 'Census Tract 604']
['Census Tract 8391']
['Census Tract 8391']
['Census Tract 814.01', 'Census Tract 2101']
['Census Tract 8391', 'Census Tract 8383', 'Census Tract 8383']
['Census Tract 2801', 'Census Tract 2101']
['Census Tract 8362', 'Census Tract 8420', 'Census Tract 2435']
['Census Tract 8382', 'Census Tract 8382']
['Census Tract 3301']
['Census Tract 8382', 'Census Tract 2216', 'Census Tract 2216', 'Census Tract 2216']
['Census Tract 8391']
['Census Tract 8391', 'Census Tract 2412']
['Census Tract 104', 'Census Tract 104']
['Census Tract 812.01', 'Census Tract 812.01', 'Census Tract 812.01']
['Census Tract 8362', 'Census Tract 817']
['Census Tract 8419', 'Census Tract 8391']
['Census Tract 6112', 'Census Tract 106']
['Census Tract 8391', 'Census Tract 3204']
['Census Tract 104', 'Census Tract 104']
['Census Tract 813', 'Census Tract 3206']
['Census Tract 2434', 'Census Tract 3204']
['Census Tract 8362', 'Census Tract 8331', 'Census Tract 3905', 'Census Tract 3105', 'Census Tract 4112']
['Census Tract 8391']
['Census Tract 2819', 'Census Tract 2801']
['Census Tract 8331', 'Census Tract 3206']
['Census Tract 8419', 'Census Tract 311', 'Census Tract 3204']
['Census Tract 8391', 'Census Tract 8419', 'Census Tract 817']
['Census Tract 2819']
['Census Tract 8391']
['Census Tract 8419', 'Census Tract 8419', 'Census Tract 3104', 'Census Tract 8399']
['Census Tract 8382', 'Census Tract 4110']
['Census Tract 3201']
['Census Tract 1612', 'Census Tract 2413']
['Census Tract 3201']
['Census Tract 814.01', 'Census Tract 3302', 'Census Tract 4111']
['Census Tract 8391']
['Census Tract 817', 'Census Tract 2819']
['Census Tract 8391']
['Census Tract 3201', 'Census Tract 8391']
['Census Tract 3201']
['Census Tract 8391', 'Census Tract 3201']
['Census Tract 104', 'Census Tract 812.01']
['Census Tract 3204', 'Census Tract 3204', 'Census Tract 502', 'Census Tract 502']
['Census Tract 8422', 'Census Tract 8396']
['Census Tract 8426', 'Census Tract 8426']
['Census Tract 2804']
['Census Tract 7201']
['Census Tract 3201', 'Census Tract 8391']
['Census Tract 818', 'Census Tract 3201']
['Census Tract 8330', 'Census Tract 3201']
['Census Tract 8382', 'Census Tract 104', 'Census Tract 8391']
['Census Tract 8410', 'Census Tract 902']
['Census Tract 3201']
['Census Tract 817']
['Census Tract 8391']
['Census Tract 2819']
['Census Tract 8390']
['Census Tract 8330', 'Census Tract 8330']
['Census Tract 319']
['Census Tract 8391', 'Census Tract 8391']
['Census Tract 815', 'Census Tract 2819']
['Census Tract 8331', 'Census Tract 8331']
['Census Tract 8391']
['Census Tract 8391']
['Census Tract 8391', 'Census Tract 7505']
['Census Tract 8391', 'Census Tract 812.01', 'Census Tract 2422']
['Census Tract 8435', 'Census Tract 8362']
['Census Tract 7608.01']
['Census Tract 3201']
['Census Tract 8419', 'Census Tract 8419']
['Census Tract 3201', 'Census Tract 1202']
['Census Tract 8391', 'Census Tract 308', 'Census Tract 302']
['Census Tract 8391']
['Census Tract 2801']
['Census Tract 4203', 'Census Tract 817']
['Census Tract 632', 'Census Tract 1005']
['Census Tract 8391', 'Census Tract 8329', 'Census Tract 8391']
['Census Tract 2002', 'Census Tract 8391']
['Census Tract 8333']
['Census Tract 8391', 'Census Tract 707']
['Census Tract 3201', 'Census Tract 817']
['Census Tract 8391']
['Census Tract 8391', 'Census Tract 3204']
['Census Tract 814.01']
['Census Tract 814.01']
['Census Tract 8391']
['Census Tract 8391']
['Census Tract 8382']
['Census Tract 8391']
['Census Tract 3204', 'Census Tract 3204']
['Census Tract 818']
['Census Tract 8326']
['Census Tract 3201']
['Census Tract 8391']
['Census Tract 4905']
['Census Tract 3204', 'Census Tract 6708', 'Census Tract 8391']
['Census Tract 8420']
['Census Tract 8391', 'Census Tract 8422', 'Census Tract 1505.01']
['Census Tract 8382', 'Census Tract 8331']

In [70]:
import json

json.dump(origin_dest_pairs, open('data/origin_pairs.json', 'w'), indent=2)

In [7]:
import json

pairs = json.load(open('data/origin_pairs.json', 'r'))

results = {}

for origin, destinations in pairs.items():
    results[origin] = {d: destinations.count(d) for d in set(destinations)}

In [9]:
json.dump(results, open('data/origin_dest_weights.json', 'w'), indent=2)